#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re
from collections import defaultdict

ROOT = Path('/Volumes/Data/Games/Baldur\'s Gate II Enhanced Edition'.replace("\\'", "'"))
OVERRIDE = ROOT / 'override'
GEN = ROOT / 'bm_tweaks' / 'generated'
IN_TPA = GEN / 'empty_container_assignments.tpa'

OUT_TIER_DIR = GEN / '23_tier_scripts'
OUT_EMPTY_TPA = GEN / '23_empty_container_tier_additions.tpa'
OUT_REPORT = ROOT / '.agent' / 'working' / '23_empty_tier_generation_report.txt'


AREA_BLOCK_RE = re.compile(r'^ACTION_IF FILE_EXISTS_IN_GAME ~([A-Za-z0-9_]+)\.ARE~ BEGIN$', re.IGNORECASE)
SET_CONTAINER_RE = re.compile(r'^\s*SET container_index = (\d+)\s*$', re.IGNORECASE)
SET_ITEM_RE = re.compile(r'^\s*SPRINT item_to_add ~([^~]+)~\s*$', re.IGNORECASE)


def map_item_to_tier(item: str) -> int:
    it = item.upper()
    if it == 'RNDTRE01':
        return 1
    if it in {'RNDTRE02', 'RNDTRE06'}:
        return 2
    if it in {'RNDTRE03', 'RNDTRE07'}:
        return 3
    if it == 'SODTRE08':
        return 4
    if it == 'SODTRE09':
        return 5
    if it in {'RNDTRE04', 'RNDTRE08'}:
        return 6
    if it in {'RNDTRE05', 'RNDTRE09', 'SODTRE07'}:
        return 7

    # Fallback heuristics for non-RNDTRE placeholders used in empty assignments.
    if it.startswith('RNDMAG'):
        return 6
    if it.startswith('RNDSCR'):
        return 3
    if it.startswith('RNDPTN'):
        return 2
    if it.startswith('RND'):
        return 3

    return 3


def tier_to_roll(tier: int) -> str:
    tier = max(1, min(7, tier))
    return f'RNDBM00{tier}'


def resolve_area(area: str, override_areas: set[str]) -> str | None:
    a = area.upper()
    # Prefer BG#### when present for EET-style naming, but only if file exists in override.
    m = re.fullmatch(r'AR(\d{4})', a)
    if m:
        bg = f'BG{m.group(1)}'
        if bg in override_areas:
            return bg
    if a in override_areas:
        return a
    return None


def parse_empty_assignments(path: Path) -> dict[str, list[tuple[int, str]]]:
    blocks: dict[str, list[tuple[int, str]]] = defaultdict(list)

    cur_area: str | None = None
    cur_container: int | None = None

    for raw in path.read_text(encoding='utf-8').splitlines():
        m = AREA_BLOCK_RE.match(raw.strip())
        if m:
            cur_area = m.group(1).upper()
            cur_container = None
            continue

        if raw.strip().upper() == 'END':
            cur_area = None
            cur_container = None
            continue

        if cur_area is None:
            continue

        m = SET_CONTAINER_RE.match(raw)
        if m:
            cur_container = int(m.group(1))
            continue

        m = SET_ITEM_RE.match(raw)
        if m and cur_container is not None:
            blocks[cur_area].append((cur_container, m.group(1).upper()))

    return blocks


def write_tier_scripts(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    for p in out_dir.glob('BMCO_T*.baf'):
        p.unlink()

    for tier in range(1, 8):
        roll = tier_to_roll(tier)
        txt = [
            '// Auto-generated by bm_tweaks/staging/scripts/gen_component23_tiers_and_empty_additions.py',
            f'// Shared tier script for container/object bonus roll tier {tier}.',
            'IF',
            '  Clicked([ANYONE])',
            f'  Global("BMCO_T{tier}_ROLLED","LOCALS",0)',
            'THEN',
            '  RESPONSE #100',
            f'    CreateItem("{roll}",0,0,0)',
            f'    SetGlobal("BMCO_T{tier}_ROLLED","LOCALS",1)',
            'END',
            ''
        ]
        (out_dir / f'BMCO_T{tier}.baf').write_text('\n'.join(txt), encoding='utf-8')


def write_empty_additions(out_path: Path, resolved: dict[str, list[tuple[int, int, str]]]) -> None:
    lines: list[str] = [
        '// Auto-generated by bm_tweaks/staging/scripts/gen_component23_tiers_and_empty_additions.py',
        '// Adds one RNDBM tier entry to empty containers from generated empty-container assignments.',
        '// Uses EET BG#### area names when those are the actual override resources.',
        ''
    ]

    for area in sorted(resolved):
        entries = resolved[area]
        lines.append(f'ACTION_IF FILE_EXISTS_IN_GAME ~{area}.ARE~ BEGIN')
        lines.append(f'  COPY_EXISTING ~{area}.ARE~ ~override~')
        for cidx, tier, src_item in entries:
            roll = tier_to_roll(tier)
            lines.append(f'    // from {src_item} -> tier {tier}')
            lines.append(f'    SET container_index = {cidx}')
            lines.append(f'    SPRINT item_to_add ~{roll}~')
            lines.append('    LPM BM_ADD_CONTAINER_ITEM')
        lines.append('  BUT_ONLY_IF_IT_CHANGES')
        lines.append('END')
        lines.append('')

    out_path.write_text('\n'.join(lines), encoding='utf-8')


def main() -> None:
    if not IN_TPA.exists():
        raise SystemExit(f'Missing input file: {IN_TPA}')

    override_areas = {p.stem.upper() for p in OVERRIDE.glob('*.ARE')}
    raw = parse_empty_assignments(IN_TPA)

    resolved: dict[str, list[tuple[int, int, str]]] = defaultdict(list)
    unresolved_areas: set[str] = set()

    for src_area, rows in raw.items():
        dst_area = resolve_area(src_area, override_areas)
        if dst_area is None:
            unresolved_areas.add(src_area)
            continue
        for cidx, item in rows:
            tier = map_item_to_tier(item)
            resolved[dst_area].append((cidx, tier, item))

    # Stable order for deterministic output.
    for area in list(resolved.keys()):
        resolved[area].sort(key=lambda t: (t[0], t[1], t[2]))

    write_tier_scripts(OUT_TIER_DIR)
    write_empty_additions(OUT_EMPTY_TPA, resolved)

    tier_counts = defaultdict(int)
    for rows in resolved.values():
        for _, tier, _ in rows:
            tier_counts[tier] += 1

    report = [
        f'Input areas in empty assignments: {len(raw)}',
        f'Resolved output areas: {len(resolved)}',
        f'Unresolved source areas skipped: {len(unresolved_areas)}',
        f'Total container additions: {sum(len(v) for v in resolved.values())}',
    ]
    for t in range(1, 8):
        report.append(f'  Tier {t}: {tier_counts[t]}')

    if unresolved_areas:
        report.append('Unresolved areas:')
        report.extend(f'  {a}' for a in sorted(unresolved_areas))

    OUT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    OUT_REPORT.write_text('\n'.join(report) + '\n', encoding='utf-8')

    print('\n'.join(report))


if __name__ == '__main__':
    main()
